'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.17929
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("D2RIC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while creating backup ähnelt.
        '''</summary>
        Friend ReadOnly Property cantCreateBackup() As String
            Get
                Return ResourceManager.GetString("cantCreateBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while creating backup folder ähnelt.
        '''</summary>
        Friend ReadOnly Property cantCreateBackupFolder() As String
            Get
                Return ResourceManager.GetString("cantCreateBackupFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while creating folder! ähnelt.
        '''</summary>
        Friend ReadOnly Property cantCreateFolder() As String
            Get
                Return ResourceManager.GetString("cantCreateFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error! Couldn&apos;t load this itembuild. ähnelt.
        '''</summary>
        Friend ReadOnly Property cantLoadItembuild() As String
            Get
                Return ResourceManager.GetString("cantLoadItembuild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while reading. ähnelt.
        '''</summary>
        Friend ReadOnly Property cantRead() As String
            Get
                Return ResourceManager.GetString("cantRead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please check your Steam path!!! ähnelt.
        '''</summary>
        Friend ReadOnly Property checkPath() As String
            Get
                Return ResourceManager.GetString("checkPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please choose a hero first. ähnelt.
        '''</summary>
        Friend ReadOnly Property chooseAHero() As String
            Get
                Return ResourceManager.GetString("chooseAHero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Client not found. ähnelt.
        '''</summary>
        Friend ReadOnly Property clientNotFound() As String
            Get
                Return ResourceManager.GetString("clientNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete backups? ähnelt.
        '''</summary>
        Friend ReadOnly Property deleteBackupsQuestion() As String
            Get
                Return ResourceManager.GetString("deleteBackupsQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        '''</summary>
        Friend ReadOnly Property errorText() As String
            Get
                Return ResourceManager.GetString("errorText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File saved. ähnelt.
        '''</summary>
        Friend ReadOnly Property fileSaved() As String
            Get
                Return ResourceManager.GetString("fileSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup not found. ähnelt.
        '''</summary>
        Friend ReadOnly Property noBackup() As String
            Get
                Return ResourceManager.GetString("noBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup folder doesn&apos;t exist. ähnelt.
        '''</summary>
        Friend ReadOnly Property noBackupFolder() As String
            Get
                Return ResourceManager.GetString("noBackupFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error! Hero maybe not implemented yet. ähnelt.
        '''</summary>
        Friend ReadOnly Property notImplemented() As String
            Get
                Return ResourceManager.GetString("notImplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Path changed successfully. ähnelt.
        '''</summary>
        Friend ReadOnly Property pathChanged() As String
            Get
                Return ResourceManager.GetString("pathChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This change requires a restart of this application. ähnelt.
        '''</summary>
        Friend ReadOnly Property restartNeeded() As String
            Get
                Return ResourceManager.GetString("restartNeeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You have unsaved changes! ähnelt.
        '''</summary>
        Friend ReadOnly Property unsavedChanges_Pt1() As String
            Get
                Return ResourceManager.GetString("unsavedChanges_Pt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you want to continue? ähnelt.
        '''</summary>
        Friend ReadOnly Property unsavedChanges_Pt2() As String
            Get
                Return ResourceManager.GetString("unsavedChanges_Pt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unsaved changes ähnelt.
        '''</summary>
        Friend ReadOnly Property unsavedChangesTitle() As String
            Get
                Return ResourceManager.GetString("unsavedChangesTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Update available!! ähnelt.
        '''</summary>
        Friend ReadOnly Property update_Pt1() As String
            Get
                Return ResourceManager.GetString("update_Pt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Your Version:  ähnelt.
        '''</summary>
        Friend ReadOnly Property update_Pt2() As String
            Get
                Return ResourceManager.GetString("update_Pt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Version:  ähnelt.
        '''</summary>
        Friend ReadOnly Property update_Pt3() As String
            Get
                Return ResourceManager.GetString("update_Pt3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Open the Download page? ähnelt.
        '''</summary>
        Friend ReadOnly Property update_Pt4() As String
            Get
                Return ResourceManager.GetString("update_Pt4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        '''</summary>
        Friend ReadOnly Property update_Title() As String
            Get
                Return ResourceManager.GetString("update_Title", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
